### ISSUE TITLE
Very expensive at startup

### ISSUE THREAD

**Issue by gegoune** [codybuell/cmp-lbdb#2]
Hi, not lazy loading cmp-lbdb in any way makes nvim startup really slow.

<img width="519" alt="noughty" src="https://user-images.githubusercontent.com/69750637/206899913-0da7e061-756f-43ad-9fc3-82f154717b1c.png">

Had a very quick look and it seems like plugin is fetching addresses at startup since all logic is in `after/plugin` - that means it runs unconditionally once plugin gets loaded.

Perhaps it could be improved such that:
- it only loads for configured filetypes, `mail` by default
- run tasks asynchronously (suggested by Lewis on gitter)
- it only populates lists on first completion invocation.

Thanks for that plugin, I use it every day.

**Comment by gwarf** [comment]
The lazy loading on a given filetype helps not impacting all the time, but it would be great to have the list be populated asynchronously when opening a mail file.
 
For the async part, maybe something like https://github.com/nvim-lua/plenary.nvim#plenaryasync could help? Plenary's async is apparently used by various other lua plugins: https://github.com/nvim-lua/plenary.nvim#plugins-using-this.

In nvim-cmp there is also https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/utils/async.lua.
