### ISSUE TITLE
Configure for specific filetypes

### ISSUE THREAD

**Issue by matthew-hennefarth** [codybuell/cmp-lbdb#5]
Is there a way to change which file types this is used for in the configuration? I see that there are some hard-coded lines [here](https://github.com/codybuell/cmp-lbdb/blob/3e7a816c16dd4045c3434ee9ad79de3417f6dbe7/lua/cmp_lbdb/init.lua#L25-L27)

```lua
function source.is_available()
    return vim.bo.filetype == 'mail' or vim.bo.filetype == 'markdown'
end
```

Maybe this could be changed into a table or list, like the blacklist?

**Comment by codybuell** [comment]
@matthew-hennefarth take a look at the [updated readme](https://github.com/codybuell/cmp-lbdb/blob/master/README.md) for an example on how to customize filetypes. Thanks for the ask.
