### ISSUE TITLE
Disable outside of the headers

### ISSUE THREAD

**Issue by euglevi** [codybuell/cmp-lbdb#7]
First of all, thank you for this nice plugin. Do you know if there is a way to disable this specific source when moving to a line outside of the headers? My list of email addresses is very long, so I would really not want to see any suggestion from this source when writing the text of the email. While I achieved disabling nvim-cmp outside of the headers, I cannot seem to find a way to disable only a specific source of nvim-cmp. Thank you for your help!

**Comment by codybuell** [comment]
Hi @euglevi, take a look at this PR and see if it would meet your needs.

@gwarf let me know if you had any other thoughts.

**Comment by gwarf** [comment]
> Hi @euglevi, take a look at [this PR](https://github.com/codybuell/cmp-lbdb/pull/8) and see if it would meet your needs.
> 
> @gwarf let me know if you had any other thoughts.

Hey @codybuell, I've tested quickly, and it seems too work great, it's a great addition!
Currently, this suits my needs very well, thanks!

**Comment by euglevi** [comment]
I have just tried it. It seems to work great and it perfectly suits my needs. Thank you very much!
